# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /usr/src/app

# Install pnpm globally
RUN npm install -g pnpm

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies (including dev dependencies) without running lifecycle scripts
RUN pnpm install --force --ignore-scripts

# Copy all source files
COPY . .

# Build the project without running the code generation step (which requires external env variables)
# Instead, directly compile the source using tsup
RUN pnpm exec tsup src/index.ts --dts --format esm && pnpm exec shx chmod +x dist/*.js

# Default command to run the MCP server
CMD ["node", "dist/index.js"]
