query GetMyNotes($limit: Int!) {
  currentUser {
    latestNotes(first: $limit) {
      totalCount
      edges {
        node {
          id
          title
          url
        }
      }
    }
  }
}
